const USER_LANG=(navigator.languages&&navigator.languages[0])||navigator.language||'en';
const USER_LANG_SHORT=USER_LANG.slice(0,2).toLowerCase();
document.documentElement.lang=USER_LANG_SHORT||'en';
console.log('Detected visitor language:',USER_LANG,'Future language pack key:',USER_LANG_SHORT);
const STOPS=[{title:'THE ENTRANCE',subtitle:'Begin your journey',action:'♛ BEGIN YOUR JOURNEY',video:'01_entrance.mp4',model:'1entrance.glb',lat:53.581724,lng:-6.610032},{title:'THE BANQUETING HALL',subtitle:'Walk the ceremonial avenue',action:' ENTER THE ROYAL FEAST',video:'02_banquet.mp4',model:'2banquethall.glb',lat:53.580742,lng:-6.611737},{title:'THE PALISADE',subtitle:'Enter the great timber circle',action:' ENTER THE GREAT ENCLOSURE',video:'03_palisade.mp4',model:'3pallisade.glb',lat:53.580630,lng:-6.611880},{title:'RATH OF THE SYNODS',subtitle:'Where sacred and royal worlds meet',action:'⚜ WITNESS THE CORONATION',video:'04_rath.mp4',model:'4rath.glb',lat:53.580279,lng:-6.612217},{title:'MOUND OF THE HOSTAGES',subtitle:'Step toward the ancient tomb',action:' DISCOVER THE ANCIENT TOMB',video:'05_mound.mp4',model:'5mound.glb',lat:53.579485,lng:-6.611493},{title:'STONE OF DESTINY',subtitle:'The Choosing',action:' TOUCH THE STONE OF KINGS',video:'06_stone.mp4',model:'6stone.glb',lat:53.578588,lng:-6.611913},{title:'TEACH CORMAIC',subtitle:'The king is revealed',action:' ENTER THE KING’S HOUSE',video:'07_cormaic.mp4',model:'7cormaic.glb',lat:53.578379,lng:-6.611426},{title:'ST PATRICK',subtitle:'The journey ends',action:'☘ HEAR PATRICK’S STORY',video:'08_patrick.mp4',model:'8patrick.glb',lat:53.580910,lng:-6.610797}];

const LANGUAGES={
 en:{name:"English",locale:"en"},
 ga:{name:"Gaeilge",locale:"ga"},
 fr:{name:"Français",locale:"fr"},
 de:{name:"Deutsch",locale:"de"},
 es:{name:"Español",locale:"es"},
 it:{name:"Italiano",locale:"it"},
 pt:{name:"Português",locale:"pt"},
 zh:{name:"中文",locale:"zh"},
 hi:{name:"हिन्दी",locale:"hi"},
 th:{name:"ไทย",locale:"th"}
};
const UI={
 en:{heroTagline:"SEAT OF THE HIGH KINGS",language:"Language",gpsTitle:"GPS Journey",gpsSubtitle:"Follow the King's Path",destination:"Destination:",enableGps:"Enable GPS Compass",gpsActive:"GPS Compass Active",jumpCurrent:"Jump to Current Stop",gpsNote:"Best used outdoors. GPS may drift by 5–20 metres around trees or buildings.",stop:"STOP",beginDefault:"♛ BEGIN THIS STOP",beginHint:"Tap the gold button to begin the cinematic story. The video opens full screen, then returns you here for AR.",storyDone:"✨ Story finished. View the AR scene next. The GPS guide is at the top of the page.",arLabel:"AR Experience",arTitle:"View in AR",arText:"Place ancient Tara into the landscape.",launchAr:"LAUNCH AR",arSoon:"AR COMING SOON",photoMain:"📸 Photo tip: when AR opens, tap the screen to show the camera button.",photoSmall:"For group photos, one person can hold the phone while others step into the scene.",nextStop:"NEXT STOP",continue:"Continue →",finishTour:"FINISH TOUR",finishButton:"Finish Tour",farewell:"Play the farewell and thank-you message",welcome:"Welcome to<br>the Hill of Tara",gateIntro:"Seat of the High Kings of Ireland. The King's Path begins at the Entrance.",startEntrance:"Begin at the Entrance",resume:"Resume previous stop",jumpNearest:"Jump to my current location",gateNote:"For the full story, start at the Entrance. If you are already at another stop, use GPS to jump nearby.",metres:"metres remaining",checking:"Checking your location…",gpsUnavailable:"GPS is not available on this device.",locationUnavailable:"Location access was not available. You can still begin at the Entrance.",locationNeeded:"Location access is needed for the compass.",enableFirst:"Enable GPS first, then I can find the closest stop.",storyComplete:"✓ STORY COMPLETE",pathContinues:"The King's Path continues",storyCompleteTitle:"The story is complete",nextLabel:"Next stop:",thanksWalk:"Thank you for walking the Hill of Tara.",compassContinue:"Use the compass at the top to continue",toNext:"to next stop",returnStart:"Return to Start",discoverMeath:"Discover Meath",thanks:"Thank you",stopVideo:"■ Stop Video",storyTold:"The story has been told.",enterHighKingWorld:"Now step into the world of the High King.",stepIntoHistory:"STEP INTO HISTORY",excellent:"Excellent.",stoodWhereKing:"You have stood where the High King once stood.",finishedContinue:"I’ve Finished — Continue"},
 ga:{name:"Gaeilge",locale:"ga",heroTagline:"SUÍ ARD-RÍTHE NA hÉIREANN",language:"Teanga",gpsTitle:"Turas GPS",gpsSubtitle:"Lean Cosán an Rí",destination:"Ceann scríbe:",enableGps:"Cumasaigh Compás GPS",gpsActive:"Compás GPS Gníomhach",jumpCurrent:"Téigh chuig an Stad Reatha",gpsNote:"Is fearr é a úsáid lasmuigh. D'fhéadfadh GPS imeacht 5–20 méadar in aice le crainn nó foirgnimh.",stop:"STAD",beginDefault:"♛ TOSAIGH AN STAD SEO",beginHint:"Tapáil an cnaipe órga chun an scéal cineamatach a thosú. Osclóidh an físeán ar lánscáileán agus fillfidh sé anseo don AR.",storyDone:"✨ Tá an scéal críochnaithe. Féach ar an radharc AR anois. Tá an treoir GPS ag barr an leathanaigh.",arLabel:"Eispéireas AR",arTitle:"Féach in AR",arText:"Cuir Teamhair ársa sa tírdhreach.",launchAr:"SEOL AR",arSoon:"AR AG TEACHT GO LUATH",photoMain:"📸 Leid ghrianghraif: nuair a osclaíonn AR, tapáil an scáileán chun cnaipe an cheamara a thaispeáint.",photoSmall:"Le haghaidh grianghraif ghrúpa, coimeádann duine amháin an fón agus seasann na daoine eile sa radharc.",nextStop:"AN CHÉAD STAD EILE",continue:"Lean ar aghaidh →",finishTour:"CRÍOCHNAIGH AN TURAS",finishButton:"Críochnaigh an Turas",farewell:"Seinn an teachtaireacht slán agus buíochais",welcome:"Fáilte go<br>Cnoc na Teamhrach",gateIntro:"Suí Ard-Ríthe na hÉireann. Tosaíonn Cosán an Rí ag an Bealach Isteach.",startEntrance:"Tosaigh ag an mBealach Isteach",resume:"Lean ón stad roimhe seo",jumpNearest:"Téigh chuig mo shuíomh reatha",gateNote:"Chun an scéal iomlán a fháil, tosaigh ag an mBealach Isteach. Má tá tú ag stad eile cheana féin, bain úsáid as GPS.",metres:"méadar fágtha",checking:"Do shuíomh á sheiceáil…",gpsUnavailable:"Níl GPS ar fáil ar an ngléas seo.",locationUnavailable:"Ní raibh rochtain ar an suíomh ar fáil. Is féidir leat tosú ag an mBealach Isteach fós.",locationNeeded:"Tá rochtain ar an suíomh ag teastáil don chompás.",enableFirst:"Cumasaigh GPS ar dtús chun an stad is gaire a aimsiú.",storyComplete:"✓ SCÉAL CRÍOCHNAITHE",pathContinues:"Leanann Cosán an Rí",storyCompleteTitle:"Tá an scéal críochnaithe",nextLabel:"An chéad stad eile:",thanksWalk:"Go raibh maith agat as siúl ar Chnoc na Teamhrach.",compassContinue:"Úsáid an compás ag barr an leathanaigh",toNext:"go dtí an chéad stad eile",returnStart:"Fill ar an Tús",discoverMeath:"Faigh amach an Mhí",thanks:"Go raibh maith agat",stopVideo:"■ Stop an Físeán"},
 fr:{name:"Français",locale:"fr",heroTagline:"SIÈGE DES HAUTS ROIS",language:"Langue",gpsTitle:"Parcours GPS",gpsSubtitle:"Suivez le chemin du Roi",destination:"Destination :",enableGps:"Activer la boussole GPS",gpsActive:"Boussole GPS active",jumpCurrent:"Aller à l'étape actuelle",gpsNote:"À utiliser de préférence à l'extérieur. Le GPS peut varier de 5 à 20 mètres près des arbres ou bâtiments.",stop:"ÉTAPE",beginDefault:"♛ COMMENCER CETTE ÉTAPE",beginHint:"Touchez le bouton doré pour lancer l'histoire. La vidéo s'ouvre en plein écran, puis revient ici pour la RA.",storyDone:"✨ Histoire terminée. Découvrez maintenant la scène en RA. Le guide GPS se trouve en haut de la page.",arLabel:"Expérience RA",arTitle:"Voir en RA",arText:"Placez l'ancienne Tara dans le paysage.",launchAr:"LANCER LA RA",arSoon:"RA BIENTÔT DISPONIBLE",photoMain:"📸 Astuce photo : lorsque la RA s'ouvre, touchez l'écran pour afficher le bouton de l'appareil photo.",photoSmall:"Pour une photo de groupe, une personne tient le téléphone pendant que les autres entrent dans la scène.",nextStop:"ÉTAPE SUIVANTE",continue:"Continuer →",finishTour:"TERMINER LA VISITE",finishButton:"Terminer la visite",farewell:"Lire le message d'adieu et de remerciement",welcome:"Bienvenue sur<br>la colline de Tara",gateIntro:"Siège des Hauts Rois d'Irlande. Le chemin du Roi commence à l'entrée.",startEntrance:"Commencer à l'entrée",resume:"Reprendre l'étape précédente",jumpNearest:"Aller à ma position actuelle",gateNote:"Pour toute l'histoire, commencez à l'entrée. Si vous êtes déjà à une autre étape, utilisez le GPS.",metres:"mètres restants",checking:"Recherche de votre position…",gpsUnavailable:"Le GPS n'est pas disponible sur cet appareil.",locationUnavailable:"La position n'était pas disponible. Vous pouvez tout de même commencer à l'entrée.",locationNeeded:"L'accès à la position est nécessaire pour la boussole.",enableFirst:"Activez d'abord le GPS pour trouver l'étape la plus proche.",storyComplete:"✓ HISTOIRE TERMINÉE",pathContinues:"Le chemin du Roi continue",storyCompleteTitle:"L'histoire est terminée",nextLabel:"Étape suivante :",thanksWalk:"Merci d'avoir parcouru la colline de Tara.",compassContinue:"Utilisez la boussole en haut pour continuer",toNext:"jusqu'à l'étape suivante",returnStart:"Retour au début",discoverMeath:"Découvrir Meath",thanks:"Merci",stopVideo:"■ Arrêter la vidéo"},
 de:{name:"Deutsch",locale:"de",heroTagline:"SITZ DER HOCHKÖNIGE",language:"Sprache",gpsTitle:"GPS-Rundgang",gpsSubtitle:"Folgen Sie dem Pfad des Königs",destination:"Ziel:",enableGps:"GPS-Kompass aktivieren",gpsActive:"GPS-Kompass aktiv",jumpCurrent:"Zum aktuellen Halt",gpsNote:"Am besten im Freien verwenden. GPS kann nahe Bäumen oder Gebäuden um 5–20 Meter abweichen.",stop:"HALT",beginDefault:"♛ DIESEN HALT BEGINNEN",beginHint:"Tippen Sie auf die goldene Schaltfläche, um die Geschichte zu starten. Das Video öffnet sich im Vollbild und kehrt danach für AR hierher zurück.",storyDone:"✨ Geschichte beendet. Sehen Sie sich nun die AR-Szene an. Die GPS-Führung befindet sich oben.",arLabel:"AR-Erlebnis",arTitle:"In AR ansehen",arText:"Platzieren Sie das alte Tara in der Landschaft.",launchAr:"AR STARTEN",arSoon:"AR BALD VERFÜGBAR",photoMain:"📸 Fototipp: Tippen Sie nach dem Öffnen von AR auf den Bildschirm, um die Kamerataste anzuzeigen.",photoSmall:"Für Gruppenfotos hält eine Person das Telefon, während die anderen in die Szene treten.",nextStop:"NÄCHSTER HALT",continue:"Weiter →",finishTour:"TOUR BEENDEN",finishButton:"Tour beenden",farewell:"Abschieds- und Dankesnachricht abspielen",welcome:"Willkommen auf<br>dem Hill of Tara",gateIntro:"Sitz der irischen Hochkönige. Der Pfad des Königs beginnt am Eingang.",startEntrance:"Am Eingang beginnen",resume:"Vorherigen Halt fortsetzen",jumpNearest:"Zu meinem aktuellen Standort",gateNote:"Beginnen Sie für die ganze Geschichte am Eingang. Befinden Sie sich bereits an einem anderen Halt, verwenden Sie GPS.",metres:"Meter verbleibend",checking:"Standort wird geprüft…",gpsUnavailable:"GPS ist auf diesem Gerät nicht verfügbar.",locationUnavailable:"Der Standort war nicht verfügbar. Sie können dennoch am Eingang beginnen.",locationNeeded:"Für den Kompass ist Standortzugriff erforderlich.",enableFirst:"Aktivieren Sie zuerst GPS, um den nächstgelegenen Halt zu finden.",storyComplete:"✓ GESCHICHTE BEENDET",pathContinues:"Der Pfad des Königs geht weiter",storyCompleteTitle:"Die Geschichte ist beendet",nextLabel:"Nächster Halt:",thanksWalk:"Danke für Ihren Rundgang über den Hill of Tara.",compassContinue:"Verwenden Sie oben den Kompass",toNext:"bis zum nächsten Halt",returnStart:"Zurück zum Anfang",discoverMeath:"Meath entdecken",thanks:"Danke",stopVideo:"■ Video stoppen"},
 es:{name:"Español",locale:"es",heroTagline:"SEDE DE LOS ALTOS REYES",language:"Idioma",gpsTitle:"Recorrido GPS",gpsSubtitle:"Sigue el Camino del Rey",destination:"Destino:",enableGps:"Activar brújula GPS",gpsActive:"Brújula GPS activa",jumpCurrent:"Ir a la parada actual",gpsNote:"Se recomienda usar al aire libre. El GPS puede desviarse entre 5 y 20 metros cerca de árboles o edificios.",stop:"PARADA",beginDefault:"♛ COMENZAR ESTA PARADA",beginHint:"Toca el botón dorado para iniciar la historia. El vídeo se abre a pantalla completa y vuelve aquí para la RA.",storyDone:"✨ Historia terminada. Ahora contempla la escena en RA. La guía GPS está en la parte superior.",arLabel:"Experiencia de RA",arTitle:"Ver en RA",arText:"Coloca la antigua Tara en el paisaje.",launchAr:"INICIAR RA",arSoon:"RA PRÓXIMAMENTE",photoMain:"📸 Consejo para fotos: cuando se abra la RA, toca la pantalla para mostrar el botón de la cámara.",photoSmall:"Para fotos de grupo, una persona puede sostener el teléfono mientras las demás entran en la escena.",nextStop:"SIGUIENTE PARADA",continue:"Continuar →",finishTour:"FINALIZAR RECORRIDO",finishButton:"Finalizar recorrido",farewell:"Reproducir el mensaje de despedida y agradecimiento",welcome:"Bienvenido a<br>la colina de Tara",gateIntro:"Sede de los Altos Reyes de Irlanda. El Camino del Rey comienza en la entrada.",startEntrance:"Comenzar en la entrada",resume:"Reanudar la parada anterior",jumpNearest:"Ir a mi ubicación actual",gateNote:"Para disfrutar de toda la historia, comienza en la entrada. Si ya estás en otra parada, utiliza el GPS.",metres:"metros restantes",checking:"Comprobando tu ubicación…",gpsUnavailable:"El GPS no está disponible en este dispositivo.",locationUnavailable:"No se pudo acceder a la ubicación. Aun así, puedes comenzar en la entrada.",locationNeeded:"La brújula necesita acceso a tu ubicación.",enableFirst:"Activa primero el GPS para encontrar la parada más cercana.",storyComplete:"✓ HISTORIA TERMINADA",pathContinues:"El Camino del Rey continúa",storyCompleteTitle:"La historia ha terminado",nextLabel:"Siguiente parada:",thanksWalk:"Gracias por recorrer la colina de Tara.",compassContinue:"Utiliza la brújula de arriba para continuar",toNext:"hasta la siguiente parada",returnStart:"Volver al inicio",discoverMeath:"Descubrir Meath",thanks:"Gracias",stopVideo:"■ Detener vídeo"},
 it:{name:"Italiano",locale:"it",heroTagline:"SEDE DEGLI ALTI RE",language:"Lingua",gpsTitle:"Percorso GPS",gpsSubtitle:"Segui il Sentiero del Re",destination:"Destinazione:",enableGps:"Attiva bussola GPS",gpsActive:"Bussola GPS attiva",jumpCurrent:"Vai alla tappa attuale",gpsNote:"Da usare preferibilmente all'aperto. Il GPS può variare di 5–20 metri vicino ad alberi o edifici.",stop:"TAPPA",beginDefault:"♛ INIZIA QUESTA TAPPA",beginHint:"Tocca il pulsante dorato per iniziare la storia. Il video si apre a schermo intero, poi torna qui per l'AR.",storyDone:"✨ Storia terminata. Ora guarda la scena in AR. La guida GPS si trova in cima alla pagina.",arLabel:"Esperienza AR",arTitle:"Visualizza in AR",arText:"Colloca l'antica Tara nel paesaggio.",launchAr:"AVVIA AR",arSoon:"AR IN ARRIVO",photoMain:"📸 Suggerimento foto: quando si apre l'AR, tocca lo schermo per mostrare il pulsante della fotocamera.",photoSmall:"Per le foto di gruppo, una persona tiene il telefono mentre le altre entrano nella scena.",nextStop:"PROSSIMA TAPPA",continue:"Continua →",finishTour:"TERMINA IL TOUR",finishButton:"Termina il tour",farewell:"Riproduci il messaggio di saluto e ringraziamento",welcome:"Benvenuto sulla<br>collina di Tara",gateIntro:"Sede degli Alti Re d'Irlanda. Il Sentiero del Re inizia all'ingresso.",startEntrance:"Inizia dall'ingresso",resume:"Riprendi la tappa precedente",jumpNearest:"Vai alla mia posizione attuale",gateNote:"Per seguire tutta la storia, inizia dall'ingresso. Se sei già presso un'altra tappa, usa il GPS.",metres:"metri rimanenti",checking:"Verifica della posizione…",gpsUnavailable:"Il GPS non è disponibile su questo dispositivo.",locationUnavailable:"La posizione non era disponibile. Puoi comunque iniziare dall'ingresso.",locationNeeded:"L'accesso alla posizione è necessario per la bussola.",enableFirst:"Attiva prima il GPS per trovare la tappa più vicina.",storyComplete:"✓ STORIA COMPLETATA",pathContinues:"Il Sentiero del Re continua",storyCompleteTitle:"La storia è completa",nextLabel:"Prossima tappa:",thanksWalk:"Grazie per aver percorso la collina di Tara.",compassContinue:"Usa la bussola in alto per continuare",toNext:"fino alla prossima tappa",returnStart:"Torna all'inizio",discoverMeath:"Scopri Meath",thanks:"Grazie",stopVideo:"■ Ferma video"},
 pt:{name:"Português",locale:"pt",heroTagline:"SEDE DOS ALTOS REIS",language:"Idioma",gpsTitle:"Percurso GPS",gpsSubtitle:"Siga o Caminho do Rei",destination:"Destino:",enableGps:"Ativar bússola GPS",gpsActive:"Bússola GPS ativa",jumpCurrent:"Ir para a paragem atual",gpsNote:"É melhor usar ao ar livre. O GPS pode variar entre 5 e 20 metros perto de árvores ou edifícios.",stop:"PARAGEM",beginDefault:"♛ INICIAR ESTA PARAGEM",beginHint:"Toque no botão dourado para iniciar a história. O vídeo abre em ecrã inteiro e depois regressa aqui para a RA.",storyDone:"✨ História concluída. Veja agora a cena em RA. O guia GPS está no topo da página.",arLabel:"Experiência de RA",arTitle:"Ver em RA",arText:"Coloque a antiga Tara na paisagem.",launchAr:"INICIAR RA",arSoon:"RA EM BREVE",photoMain:"📸 Dica de fotografia: quando a RA abrir, toque no ecrã para mostrar o botão da câmara.",photoSmall:"Para fotografias de grupo, uma pessoa segura o telefone enquanto as outras entram na cena.",nextStop:"PRÓXIMA PARAGEM",continue:"Continuar →",finishTour:"TERMINAR VISITA",finishButton:"Terminar visita",farewell:"Reproduzir a mensagem de despedida e agradecimento",welcome:"Bem-vindo à<br>Colina de Tara",gateIntro:"Sede dos Altos Reis da Irlanda. O Caminho do Rei começa na entrada.",startEntrance:"Começar na entrada",resume:"Retomar a paragem anterior",jumpNearest:"Ir para a minha localização atual",gateNote:"Para seguir toda a história, comece na entrada. Se já estiver noutra paragem, utilize o GPS.",metres:"metros restantes",checking:"A verificar a sua localização…",gpsUnavailable:"O GPS não está disponível neste dispositivo.",locationUnavailable:"Não foi possível obter a localização. Ainda pode começar na entrada.",locationNeeded:"É necessário acesso à localização para a bússola.",enableFirst:"Ative primeiro o GPS para encontrar a paragem mais próxima.",storyComplete:"✓ HISTÓRIA CONCLUÍDA",pathContinues:"O Caminho do Rei continua",storyCompleteTitle:"A história terminou",nextLabel:"Próxima paragem:",thanksWalk:"Obrigado por percorrer a Colina de Tara.",compassContinue:"Use a bússola no topo para continuar",toNext:"até à próxima paragem",returnStart:"Voltar ao início",discoverMeath:"Descobrir Meath",thanks:"Obrigado",stopVideo:"■ Parar vídeo"},
 zh:{name:"中文",locale:"zh",heroTagline:"爱尔兰至高王之地",language:"语言",gpsTitle:"GPS 导览",gpsSubtitle:"沿着国王之路前行",destination:"目的地：",enableGps:"启用 GPS 指南针",gpsActive:"GPS 指南针已启用",jumpCurrent:"前往当前站点",gpsNote:"建议在户外使用。树木或建筑附近的 GPS 可能会偏移 5–20 米。",stop:"第",beginDefault:"♛ 开始此站",beginHint:"点击金色按钮开始故事。视频将全屏播放，之后返回此页面体验增强现实。",storyDone:"✨ 故事已结束。接下来查看增强现实场景。GPS 导览位于页面顶部。",arLabel:"增强现实体验",arTitle:"在 AR 中查看",arText:"将古代塔拉呈现在真实景观中。",launchAr:"启动 AR",arSoon:"AR 即将推出",photoMain:"📸 拍照提示：AR 打开后，点击屏幕即可显示相机按钮。",photoSmall:"拍摄合照时，可由一人拿手机，其他人走进场景。",nextStop:"下一站",continue:"继续 →",finishTour:"结束导览",finishButton:"结束导览",farewell:"播放告别与感谢信息",welcome:"欢迎来到<br>塔拉山",gateIntro:"这里是爱尔兰至高王之地。国王之路从入口开始。",startEntrance:"从入口开始",resume:"继续上一站",jumpNearest:"前往我的当前位置",gateNote:"要体验完整故事，请从入口开始。如果您已经在其他站点，可使用 GPS 定位附近站点。",metres:"米剩余",checking:"正在检查您的位置…",gpsUnavailable:"此设备不支持 GPS。",locationUnavailable:"无法获取位置。您仍可从入口开始。",locationNeeded:"指南针需要位置权限。",enableFirst:"请先启用 GPS，以查找最近的站点。",storyComplete:"✓ 故事已完成",pathContinues:"国王之路继续",storyCompleteTitle:"故事已经结束",nextLabel:"下一站：",thanksWalk:"感谢您游览塔拉山。",compassContinue:"使用页面顶部的指南针继续",toNext:"到下一站",returnStart:"返回起点",discoverMeath:"探索米斯郡",thanks:"谢谢",stopVideo:"■ 停止视频"},
 hi:{name:"हिन्दी",locale:"hi",heroTagline:"आयरलैंड के उच्च राजाओं का आसन",language:"भाषा",gpsTitle:"GPS यात्रा",gpsSubtitle:"राजा के मार्ग का अनुसरण करें",destination:"गंतव्य:",enableGps:"GPS कम्पास चालू करें",gpsActive:"GPS कम्पास सक्रिय",jumpCurrent:"वर्तमान पड़ाव पर जाएँ",gpsNote:"बाहर उपयोग करना सर्वोत्तम है। पेड़ों या इमारतों के पास GPS 5–20 मीटर तक भटक सकता है।",stop:"पड़ाव",beginDefault:"♛ यह पड़ाव शुरू करें",beginHint:"कहानी शुरू करने के लिए सुनहरा बटन दबाएँ। वीडियो पूर्ण स्क्रीन में खुलेगा और फिर AR के लिए यहाँ लौटेगा।",storyDone:"✨ कहानी समाप्त हुई। अब AR दृश्य देखें। GPS मार्गदर्शक पृष्ठ के ऊपर है।",arLabel:"AR अनुभव",arTitle:"AR में देखें",arText:"प्राचीन तारा को वास्तविक परिदृश्य में रखें।",launchAr:"AR शुरू करें",arSoon:"AR जल्द आ रहा है",photoMain:"📸 फोटो सुझाव: AR खुलने पर कैमरा बटन दिखाने के लिए स्क्रीन पर टैप करें।",photoSmall:"समूह फोटो के लिए एक व्यक्ति फोन पकड़े और बाकी लोग दृश्य में खड़े हों।",nextStop:"अगला पड़ाव",continue:"आगे बढ़ें →",finishTour:"यात्रा समाप्त करें",finishButton:"यात्रा समाप्त करें",farewell:"विदाई और धन्यवाद संदेश चलाएँ",welcome:"तारा की पहाड़ी पर<br>आपका स्वागत है",gateIntro:"आयरलैंड के उच्च राजाओं का आसन। राजा का मार्ग प्रवेश द्वार से शुरू होता है।",startEntrance:"प्रवेश द्वार से शुरू करें",resume:"पिछला पड़ाव जारी रखें",jumpNearest:"मेरे वर्तमान स्थान पर जाएँ",gateNote:"पूरी कहानी के लिए प्रवेश द्वार से शुरू करें। यदि आप किसी अन्य पड़ाव पर हैं, तो GPS का उपयोग करें।",metres:"मीटर शेष",checking:"आपका स्थान जाँचा जा रहा है…",gpsUnavailable:"इस उपकरण पर GPS उपलब्ध नहीं है।",locationUnavailable:"स्थान उपलब्ध नहीं था। फिर भी आप प्रवेश द्वार से शुरू कर सकते हैं।",locationNeeded:"कम्पास के लिए स्थान की अनुमति आवश्यक है।",enableFirst:"निकटतम पड़ाव खोजने के लिए पहले GPS चालू करें।",storyComplete:"✓ कहानी पूरी हुई",pathContinues:"राजा का मार्ग जारी है",storyCompleteTitle:"कहानी पूरी हो गई",nextLabel:"अगला पड़ाव:",thanksWalk:"तारा की पहाड़ी की यात्रा के लिए धन्यवाद।",compassContinue:"जारी रखने के लिए ऊपर दिए कम्पास का उपयोग करें",toNext:"अगले पड़ाव तक",returnStart:"शुरुआत पर लौटें",discoverMeath:"मीथ की खोज करें",thanks:"धन्यवाद",stopVideo:"■ वीडियो रोकें"},
 th:{"name":"ไทย","locale":"th","heroTagline":"ที่ประทับของกษัตริย์สูงสุดแห่งไอร์แลนด์","language":"ภาษา","gpsTitle":"การเดินทางด้วย GPS","gpsSubtitle":"เดินตามเส้นทางของกษัตริย์","destination":"จุดหมาย:","enableGps":"เปิดเข็มทิศ GPS","gpsActive":"เข็มทิศ GPS ทำงานแล้ว","jumpCurrent":"ไปยังจุดแวะปัจจุบัน","gpsNote":"เหมาะสำหรับใช้งานกลางแจ้ง GPS อาจคลาดเคลื่อน 5–20 เมตรใกล้ต้นไม้หรืออาคาร","stop":"จุดแวะ","beginDefault":"♛ เริ่มจุดแวะนี้","beginHint":"แตะปุ่มสีทองเพื่อเริ่มเรื่องราวแบบภาพยนตร์ วิดีโอจะเปิดเต็มหน้าจอ แล้วกลับมาที่นี่เพื่อสัมผัส AR","storyDone":"✨ เรื่องราวจบแล้ว ต่อไปเข้าสู่ฉาก AR","arLabel":"ประสบการณ์ AR","arTitle":"ชมใน AR","arText":"นำทาราในอดีตกลับมาสู่ภูมิทัศน์จริง","launchAr":"เริ่ม AR","arSoon":"AR จะเปิดให้ใช้เร็ว ๆ นี้","photoMain":"📸 เคล็ดลับถ่ายภาพ: เมื่อ AR เปิดขึ้น ให้แตะหน้าจอเพื่อแสดงปุ่มกล้อง","photoSmall":"สำหรับภาพหมู่ ให้คนหนึ่งถือโทรศัพท์และให้คนอื่นเข้าไปยืนในฉาก","nextStop":"จุดแวะถัดไป","continue":"ดำเนินต่อ →","finishTour":"จบทัวร์","finishButton":"จบทัวร์","farewell":"เล่นข้อความอำลาและขอบคุณ","welcome":"ยินดีต้อนรับสู่<br>เนินเขาทารา","gateIntro":"ที่ประทับของกษัตริย์สูงสุดแห่งไอร์แลนด์ เส้นทางของกษัตริย์เริ่มต้นที่ทางเข้า","startEntrance":"เริ่มที่ทางเข้า","resume":"กลับไปยังจุดแวะก่อนหน้า","jumpNearest":"ไปยังตำแหน่งปัจจุบันของฉัน","gateNote":"เพื่อรับฟังเรื่องราวทั้งหมด โปรดเริ่มที่ทางเข้า หากคุณอยู่ใกล้จุดแวะอื่นแล้ว ให้ใช้ GPS","metres":"เมตรที่เหลือ","checking":"กำลังตรวจสอบตำแหน่งของคุณ…","gpsUnavailable":"อุปกรณ์นี้ไม่รองรับ GPS","locationUnavailable":"ไม่สามารถเข้าถึงตำแหน่งได้ คุณยังสามารถเริ่มที่ทางเข้าได้","locationNeeded":"ต้องอนุญาตการเข้าถึงตำแหน่งเพื่อใช้เข็มทิศ","enableFirst":"โปรดเปิด GPS ก่อน เพื่อค้นหาจุดแวะที่ใกล้ที่สุด","storyComplete":"✓ เรื่องราวเสร็จสมบูรณ์","pathContinues":"เส้นทางของกษัตริย์ดำเนินต่อไป","storyCompleteTitle":"เรื่องราวจบแล้ว","nextLabel":"จุดแวะถัดไป:","thanksWalk":"ขอบคุณที่ร่วมเดินทางบนเนินเขาทารา","compassContinue":"ใช้เข็มทิศด้านบนเพื่อเดินทางต่อ","toNext":"ไปยังจุดแวะถัดไป","returnStart":"กลับไปจุดเริ่มต้น","discoverMeath":"ค้นพบมีธ","thanks":"ขอบคุณ","stopVideo":"■ หยุดวิดีโอ","storyTold":"เรื่องราวได้ถูกถ่ายทอดแล้ว","enterHighKingWorld":"ตอนนี้ ก้าวเข้าสู่โลกของกษัตริย์สูงสุด","stepIntoHistory":"ก้าวเข้าสู่ประวัติศาสตร์","excellent":"ยอดเยี่ยม","stoodWhereKing":"คุณได้ยืนอยู่ในสถานที่เดียวกับที่กษัตริย์สูงสุดเคยยืน","finishedContinue":"ฉันชมเสร็จแล้ว — ดำเนินต่อ"}
};
const STOP_I18N={
 en:[
  ["THE ENTRANCE","Begin your journey","♛ BEGIN YOUR JOURNEY"],
  ["THE BANQUETING HALL","Walk the ceremonial avenue","ENTER THE ROYAL FEAST"],
  ["THE PALISADE","Enter the great timber circle","ENTER THE GREAT ENCLOSURE"],
  ["RATH OF THE SYNODS","Where sacred and royal worlds meet","⚜ WITNESS THE CORONATION"],
  ["MOUND OF THE HOSTAGES","Step toward the ancient tomb","DISCOVER THE ANCIENT TOMB"],
  ["STONE OF DESTINY","The Choosing","TOUCH THE STONE OF KINGS"],
  ["TEACH CORMAIC","The king is revealed","ENTER THE KING’S HOUSE"],
  ["ST PATRICK","The journey ends","☘ HEAR PATRICK’S STORY"]
 ],
 ga:[
  ["AN BEALACH ISTEACH","Cuir tús le do thuras","♛ TOSAIGH DO THURAS"],
  ["AN HALLA FÉASTA","Siúil an bealach searmanais","TÉIGH ISTEACH SA FÉASTA RÍOGA"],
  ["AN PAILISÁD","Téigh isteach sa chiorcal mór adhmaid","TÉIGH ISTEACH SA MHÓR-IAMH"],
  ["RÁTH NA SIONAD","Áit a dtagann an saol naofa agus ríoga le chéile","⚜ FEIC AN CORÓNÚ"],
  ["DUMHA NA nGIALL","Téigh i dtreo na tuama ársa","FAIGH AMACH AN TUAMA ÁRSA"],
  ["LIA FÁIL","An Roghnú","TEAGMHÁIL LE CLOCH NA RÍTHE"],
  ["TEACH CORMAIC","Nochtar an rí","TÉIGH ISTEACH I dTEACH AN RÍ"],
  ["NAOMH PÁDRAIG","Críochnaíonn an turas","☘ ÉIST LE SCÉAL PHÁDRAIG"]
 ],
 fr:[
  ["L'ENTRÉE","Commencez votre voyage","♛ COMMENCER LE VOYAGE"],
  ["LA SALLE DES BANQUETS","Parcourez l'avenue cérémonielle","ENTRER DANS LE FESTIN ROYAL"],
  ["LA PALISSADE","Entrez dans le grand cercle de bois","ENTRER DANS LA GRANDE ENCEINTE"],
  ["RATH DES SYNODES","Quand les mondes sacré et royal se rencontrent","⚜ ASSISTER AU COURONNEMENT"],
  ["LE TUMULUS DES OTAGES","Approchez de l'ancien tombeau","DÉCOUVRIR L'ANCIEN TOMBEAU"],
  ["LA PIERRE DU DESTIN","Le Choix","TOUCHER LA PIERRE DES ROIS"],
  ["TEACH CORMAIC","Le roi se révèle","ENTRER DANS LA MAISON DU ROI"],
  ["SAINT PATRICK","Le voyage se termine","☘ ÉCOUTER L'HISTOIRE DE PATRICK"]
 ],
 de:[
  ["DER EINGANG","Beginnen Sie Ihre Reise","♛ REISE BEGINNEN"],
  ["DIE FESTHALLE","Gehen Sie die Zeremonialallee entlang","ZUM KÖNIGLICHEN FEST"],
  ["DIE PALISADE","Betreten Sie den großen Holzkreis","DIE GROSSE EINFRIEDUNG BETRETEN"],
  ["RATH DER SYNODEN","Wo sich heilige und königliche Welten begegnen","⚜ DIE KRÖNUNG ERLEBEN"],
  ["HÜGEL DER GEISELN","Nähern Sie sich dem alten Grab","DAS ALTE GRAB ENTDECKEN"],
  ["STEIN DES SCHICKSALS","Die Erwählung","DEN STEIN DER KÖNIGE BERÜHREN"],
  ["TEACH CORMAIC","Der König wird offenbart","DAS HAUS DES KÖNIGS BETRETEN"],
  ["ST. PATRICK","Die Reise endet","☘ PATRICKS GESCHICHTE HÖREN"]
 ],
 es:[
  ["LA ENTRADA","Comienza tu viaje","♛ COMENZAR EL VIAJE"],
  ["EL SALÓN DE BANQUETES","Recorre la avenida ceremonial","ENTRAR EN EL BANQUETE REAL"],
  ["LA EMPALIZADA","Entra en el gran círculo de madera","ENTRAR EN EL GRAN RECINTO"],
  ["RATH DE LOS SÍNODOS","Donde se encuentran lo sagrado y lo real","⚜ PRESENCIAR LA CORONACIÓN"],
  ["TÚMULO DE LOS REHENES","Acércate a la tumba antigua","DESCUBRIR LA TUMBA ANTIGUA"],
  ["PIEDRA DEL DESTINO","La Elección","TOCAR LA PIEDRA DE LOS REYES"],
  ["TEACH CORMAIC","El rey se revela","ENTRAR EN LA CASA DEL REY"],
  ["SAN PATRICIO","El viaje termina","☘ ESCUCHAR LA HISTORIA DE PATRICIO"]
 ],
 it:[
  ["L'INGRESSO","Inizia il tuo viaggio","♛ INIZIA IL VIAGGIO"],
  ["LA SALA DEI BANCHETTI","Percorri il viale cerimoniale","ENTRA NEL BANCHETTO REALE"],
  ["LA PALIZZATA","Entra nel grande cerchio di legno","ENTRA NEL GRANDE RECINTO"],
  ["RATH DEI SINODI","Dove il mondo sacro incontra quello regale","⚜ ASSISTI ALL'INCORONAZIONE"],
  ["TUMULO DEGLI OSTAGGI","Avvicinati all'antica tomba","SCOPRI L'ANTICA TOMBA"],
  ["PIETRA DEL DESTINO","La Scelta","TOCCA LA PIETRA DEI RE"],
  ["TEACH CORMAIC","Il re viene rivelato","ENTRA NELLA CASA DEL RE"],
  ["SAN PATRIZIO","Il viaggio termina","☘ ASCOLTA LA STORIA DI PATRIZIO"]
 ],
 pt:[
  ["A ENTRADA","Comece a sua viagem","♛ COMEÇAR A VIAGEM"],
  ["O SALÃO DE BANQUETES","Percorra a avenida cerimonial","ENTRAR NO BANQUETE REAL"],
  ["A PALIÇADA","Entre no grande círculo de madeira","ENTRAR NO GRANDE RECINTO"],
  ["RATH DOS SÍNODOS","Onde os mundos sagrado e real se encontram","⚜ ASSISTIR À COROAÇÃO"],
  ["TÚMULO DOS REFÉNS","Aproxime-se do túmulo antigo","DESCOBRIR O TÚMULO ANTIGO"],
  ["PEDRA DO DESTINO","A Escolha","TOCAR NA PEDRA DOS REIS"],
  ["TEACH CORMAIC","O rei é revelado","ENTRAR NA CASA DO REI"],
  ["SÃO PATRÍCIO","A viagem termina","☘ OUVIR A HISTÓRIA DE PATRÍCIO"]
 ],
 zh:[
  ["入口","开始您的旅程","♛ 开始旅程"],
  ["宴会大厅","沿着仪式大道前行","进入王室宴会"],
  ["木栅栏","进入巨大的木制圆环","进入大型围场"],
  ["宗教会议之环","神圣与王权交汇之地","⚜ 见证加冕"],
  ["人质墓冢","走近古老墓室","探索古老墓室"],
  ["命运之石","王者之选","触摸王者之石"],
  ["科马克之屋","国王显现","进入国王之屋"],
  ["圣帕特里克","旅程结束","☘ 聆听帕特里克的故事"]
 ],
 hi:[
  ["प्रवेश द्वार","अपनी यात्रा शुरू करें","♛ यात्रा शुरू करें"],
  ["भोज कक्ष","अनुष्ठानिक मार्ग पर चलें","राजकीय भोज में प्रवेश करें"],
  ["लकड़ी की परिधि","विशाल लकड़ी के घेरे में प्रवेश करें","महान परिसर में प्रवेश करें"],
  ["राथ ऑफ द सिनॉड्स","जहाँ पवित्र और राजसी संसार मिलते हैं","⚜ राज्याभिषेक देखें"],
  ["बंधकों का समाधि-टीला","प्राचीन समाधि की ओर बढ़ें","प्राचीन समाधि खोजें"],
  ["भाग्य का पत्थर","राजा का चयन","राजाओं के पत्थर को छुएँ"],
  ["टीच कॉर्मैक","राजा प्रकट होता है","राजा के घर में प्रवेश करें"],
  ["सेंट पैट्रिक","यात्रा समाप्त होती है","☘ पैट्रिक की कहानी सुनें"]
 ],
 th:[["ทางเข้า","เริ่มต้นการเดินทางของคุณ","♛ เริ่มต้นการเดินทาง"],["โถงจัดเลี้ยง","เดินไปตามเส้นทางพิธีการ","เข้าสู่งานเลี้ยงของราชสำนัก"],["แนวรั้วไม้","เข้าสู่วงล้อมไม้ขนาดใหญ่","เข้าสู่เขตล้อมอันยิ่งใหญ่"],["ราธแห่งสภาศาสนา","จุดที่โลกศักดิ์สิทธิ์และราชสำนักมาบรรจบกัน","⚜ ร่วมเป็นสักขีพยานในพิธีราชาภิเษก"],["เนินสุสานตัวประกัน","ก้าวเข้าใกล้สุสานโบราณ","ค้นพบสุสานโบราณ"],["ศิลาแห่งชะตากรรม","การเลือกกษัตริย์","สัมผัสศิลาแห่งกษัตริย์"],["ทีช คอร์แม็ก","กษัตริย์ปรากฏตัว","เข้าสู่เรือนของกษัตริย์"],["นักบุญแพทริก","การเดินทางสิ้นสุดลง","☘ ฟังเรื่องราวของนักบุญแพทริก"]]
};
